### ISSUE TITLE
Setup Tests

### ISSUE THREAD

**Issue by MaxAlberti** [DHBW-SE-2023/YAAC#12]
The tests should cover current code, including the UI. Test syntax is documented in the fyne documentation. 
The tests should automatically be executed when building using make.

**Comment by V1nzent** [comment]
- all tests are separated in the test module
- create a testfile template that shows how the tests work
- explain how to name the testfiles and testfunctions
- write a README where the test syntax is shorty explained

**Comment by V1nzent** [comment]
- tests can be executed manually
- tests are automatically executed when building the project using make build
