### ISSUE TITLE
Font on Welcome page

### ISSUE THREAD

**Issue by EvaMatz** [DHBW-SE-2023/YAAC#146]
**Describe the bug**
Font on Welcome page not fully visible while being on full screen (there's also no possibility to make the window smaller on the left/right)

**To Reproduce**
1. Run `make run`
2. Open YAAC
3. See error

**Expected behavior**
Font on Welcome Page should be fully visible 

**Screenshots**

![Image](https://github.com/DHBW-SE-2023/YAAC/assets/114435451/e2b5e8c3-12e4-4fa3-a1c3-a112e75ccb96)

(hope that works)

**Desktop (please complete the following information):**
 - OS: macOS Intel

**Comment by danielSiegt08** [comment]
Bug should be removed, @EvaMatz please confirm
