### ISSUE TITLE
Image Processing: extracting the table information

### ISSUE THREAD

**Issue by EvaMatz** [DHBW-SE-2023/YAAC#21]
### Description
This is the second major step in the pipeline. We have an image that shows the table of the students' names and the signatures. This table is presented from an orthogonal view to ease further processing.
At first the image needs to be converted to a binary image. This is the preparation which occurs before we start to extract the table itself.
Then we extract the horizontal and vertical lines that make up the table grid be opening the image with the horizontal and vertical kernels (of the form Nx1 and 1xN, respectively). After recombining the vertical and horizontal lines, we extract all contours.
We sort the contours into an `[rows][cols]image.Rectangle` from top left to bottom right. Then we filter any undesirable columns (mainly those that have a zero width or height)
We save the resulting columns together with the image in a struct.

### Criteria for acceptance
Take in an image and build a `Table` struct from the data shown in the image. A `Table` contains its cells in a matrix of `image.Rectangle`s in row-major. It also needs to identify the cells of a table reliably. The table for a TI list should always have 3 columns. The logic for creating a table from an image is responsible for providing that result.

**Comment by leandergmeiner** [comment]
The above described logic is mainly implemented in one main function in `internal/cv/table.go`.
This function is
```go
func NewTable(img gocv.Mat) Table
```
This takes the prepared image from the previous step in the pipeline. The prepared image is the centered view of the table. It is
a binary image. 
In the future we might not want to take in a binary image, as the previous step in the pipeline will probably return the original image, which just underwent a perspective transform (Mainly because of the GUI and showing the table image to the user).

**Comment by leandergmeiner** [comment]
> It is a binary image. In the future we might not want to take in a binary image, as the previous step in the pipeline will probably return the original image, which just underwent a perspective transform (Mainly because of the GUI and showing the table image to the user).

We now do the same type of preprocessing in `NewTable` as in `FindTable`, to account for the probable change of input image into `NewTable`.

**Comment by leandergmeiner** [comment]
The basic idea works, though there are many irregularities that I am going to have to take care of, as we are far away yet from the designated goal of 3 columns per row. It currently recognizes a lot more columns per row. Though I also have not put any checks in place for the columns except checking whether the width or height of the columns is 0.

**Comment by leandergmeiner** [comment]
> The basic idea works, though there are many irregularities that I am going to have to take care of, as we are far away yet from the designated goal of 3 columns per row. It currently recognizes a lot more columns per row. Though I also have not put any checks in place for the columns except checking whether the width or height of the columns is 0.

I added now additional checks, that check whether the cells have a minimum height and minimum width. MinHeight and minWidth are computed as follows (the values were found by trial and error, and those worked best):
```go
minWidth := int(maxWidth * 0.04)
minHeight := int(maxHeight * 0.02)
```

**Comment by leandergmeiner** [comment]
Now only tests need to be added for this feature. 

### Test for row length
The first test looks like this and tests the functions `FindTable` and `NewTable` (as `FindTable` is a bit difficult to test by itself, as it outputs an image):
1. Take in an image of a TI list
2. Use `FindTable` on it
3. Use `NewTable` on it
4. Check that for each row the length of the columns in that row is exactly 3

### Test for image equality
Take in an image of a TI list.
1. Use FindTable on it
2. Save the result as test data.
3. Future test runs: 
3.1. Take in an image of a TI list
3.2. Use `FindTable` on it
3.3. Assert equality of the result of `FindTable` with the saved result

This test is probably inpractical for development, as the implementation of `FindTable` likely changes in the future and with it changes the resulting image. Maybe once were 100% happy with the result of `FindTable` this test is feasible, but only for the current "frozen" version, breaking again with future development on this function.
