### ISSUE TITLE
Image Processing: Find the table and warp the perspective

### ISSUE THREAD

**Issue by EvaMatz** [DHBW-SE-2023/YAAC#23]
### Description
The first step of the image pipeline is to find the table we are interested in. The image of the sheet of paper with the table of students along with their signatures on it is taken by a mobile device. Therefore the image contains more than the sheet of paper itself (like the surrounding desk).
Also the image might be taken at a tilt, which could mess with the further steps in the pipeline.
We need to transform the image in such a way, that only the table is in the image and that the image shows the image from an orthogonal view (think CamScanner for the mobile phone).

To achieve this we first need to detect the table. We assume that we can find the largest rectangle with black borders and skip the step of finding the sheet of paper first. We can assume this, because most desks in the DHBW have a white surface, therefore the paper blends in with the table and we can instantly retrieve the largest rectangle. *This might be a future source of errors*.
When we get the contour of the largest rectangle, which is the table with the signatures, we can use it to do a WarpPerspective on the image (effectively a reverse perspective transform) which does the desired transformation of the original image.

### Criteria for acceptance
Given a image, find the largest black rectangle and do a reverse perspective transform of it s.t. the result shows the table from an orthogonal view and the resulting image only consists of the table.

**Comment by leandergmeiner** [comment]
To start with image processing, we should use a new module. The module is called cv (short for computer vision). It contains all code of our application responsible for doing any kind of image processing. 
The module's code should be used only internally, its library functions are not stable and could change at any moment. Therefore we put it in the `internal/` folder. 
The path for the module is therefore `internal/cv`.
