### ISSUE TITLE
Image Processing: Signature validation

### ISSUE THREAD

**Issue by EvaMatz** [DHBW-SE-2023/YAAC#25]
### Description
For all rows with a student name, extract the signature field, which is located right to it. Column 2 contains the student name and column 3 contains the signatures. Check for each signature field if the there is only one signature in the signature column. If there is not exactly one signature detected in each signature field, mark the row as invalid.
The detecting is performed by finding all contours in the signature field image, then getting the bounding boxes of them. For each bounding box we then check if the bounding box has a minimum size, else we skip it. We then check if the count of the remaining bounding boxes is equal to 1 and if so we mark the column as valid. Else we mark the column as invalid.

### Criteria for acceptance
Given an BGR image, which shows the signature field, detect all signatures in the image. If not exactly one signature was detected, mark the row as invalid. The accuracy must be 100%.

**Comment by leandergmeiner** [comment]
I think, that we should also contract bounding boxes, that are relatively close together into a single bounding box, as the most definitely belong to the same signature. I'm thinking that we should contract them, if they have a dx of less or equal to 1% of the max width.

**Comment by leandergmeiner** [comment]
Closed with merge request.
