### ISSUE TITLE
Database: Research Database

### ISSUE THREAD

**Issue by EvaMatz** [DHBW-SE-2023/YAAC#27]
Find best database after following criteria (sorted in descending order):
- Simple to use
- Query speed

**Comment by JonasZagst** [comment]
# Deciding for a data storage solution

While researching the possible database solutions for **YAAC** it became apparent that there are compromises with every solution.

## Why not full DBMS

Using a full Database Management System could make data management efficient and offers great performance and extensibility but such systems would need to be installed on the machine and initialized they can not easily be packaged. Requiring no additional setup and possibly only one executable should remain the focus.

## SQLite

SQLite is supported in GO and provides an minimal relational database which could be packaged together with the rest of **YAAC**. It is still performant and offers many functions and extensibility.

**Comment by V1nzent** [comment]
This issue has the status done, but it is not closed. Please give a coherent status update.

**Comment by MaxAlberti** [comment]
> # Deciding for a data storage solution
> 
> While researching the possible database solutions for **YAAC** it became apparent that there are compromises with every solution.
> ## Why not full DBMS
> 
> Using a full Database Management System could make data management efficient and offers great performance and extensibility but such systems would need to be installed on the machine and initialized they can not easily be packaged. Requiring no additional setup and possibly only one executable should remain the focus.
> ## SQLite
> 
> SQLite is supported in GO and provides an minimal relational database which could be packaged together with the rest of **YAAC**. It is still performant and offers many functions and extensibility. It also supports saving binary data directly which can be used to store images up to 1GB per default.

Closed with decison falling on SQLite
