### ISSUE TITLE
Database: Setup

### ISSUE THREAD

**Issue by EvaMatz** [DHBW-SE-2023/YAAC#28]
The database has to save the following information:

- For every course: List of students, studies speciality identifier (e.g. "TIK"), lecturer, list of dates marking for each student whether they were present or not
- List could look similar to following table:
   | Course | Name | 22.11.2023 | 23.11.2023 | 24.11.2023 |
   | --- | --- | --- | --- | --- | 
   | TIT  | M. Mustermann | Present | Absent | Present |
   | TIK | M. Musterfrau | Present | Present | Present |
- The picture of the attendance sheets are also saved in the database, therefore the database has to be able to save images

**Comment by JonasZagst** [comment]
# Database definition and model

The [Databse ERM](https://github.com/DHBW-SE-2023/Wiki/blob/main/Diagrams/Database/DB-Entwurf.png)
shows a high level overview planned out with everyone involved. It defines all tabels and their relation needed for the basic program and leaves expandability.

## Data dictionary

* **Student**: 
    * **StudentId**:  INTEGER PRIMARY KEY
    * LName: VARCHAR(50) NOT NULL
    * VName: VARCHAR(50) NOT NULL
    * StatusOfMatriculation: BOOLEAN Default=True NOT NULL

* **AttendanceList**:
     * **ListId**: INTEGER PRIMARY KEY
     * List: BLOB NOT NULL
     *  Date: DATETIME NOT NULL
     *  Course: VARCHAR(12) NOT NULL

* **Attendance**:
    * **Date**: DATE PRIMARY KEY
    * **StudentId**: INTEGER REFERENCES Student (StudentId)
    *  Attendance: BOOLEAN Default=False NOT NULL
