### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by Erix0815** [DHBW-SE-2023/YAAC#39]
Currently there is no easy way to ship our software.
Go as well as Fyne support packaging and cross-compilation.
GoCV and other dependencies also should to be linked statically to avoid troubles when deploying
(alternatively GoCV could be shipped seperately as .dll/.so)

-> implement fluent Packaging-Workflow using Go/Fyne
-> explore ways to comfortably ship GoCV
-> abstract the process using make

**Comment by Erix0815** [comment]
Trying to avoid problems with cross-packaging by compiling on windows directly turned out to be a dead end.
Niether @leandergmeiner, @MaxAlberti or @Erix0815 managed to correctly install GoCV on Windows.
We tried installing directly from the Reporitory and via a Package-Manager by Microsoft.

Cross-Pachaging from Linux via Fyne-Cross works via a Docker-Container running windows, and therefore fails because GoCV is not installed.

I suggest only supporting Linux for now and maybe adding support for Windows if we have spare time in the end.
Alternatively @MaxAlberti suggested looking into containerisation, i.e. running our software inside a Linux VM on any OS.

**Comment by leandergmeiner** [comment]
I think it would be possible to compile GoCV on Windows, if we use MinGW-w64. This is also suggested by the [GoCV documentation](https://gocv.io/getting-started/windows/).
Another possibility would be to try to compile it with Clang. When building GoCV on Windows without GCC an error occurs, which says, that it could not `exec g++`. Clang is quite compatible with GCC in terms of compiler flags and language extensions, so if we could trick GoCV into using Clang instead of g++ it might also work.
The easier solution by far though is to just install MinGW-w64 and try build GoCV with that.

**Comment by MaxAlberti** [comment]
https://github.com/nomacs/nomacs/blob/master/scripts/make.py project including opencv with buildscript for windows and linux.

**Comment by MaxAlberti** [comment]
### We can now run the YAAC container on (any) linux system!
1. Run `xhost +local:docker` to enable display acess
2. Start the container
2.1 Docker: `docker run -it --rm -v $XAUTHORITY:$XAUTHORITY:ro -v /tmp/.X11-unix:/tmp/.X11-unix:ro  -e "DISPLAY" ghcr.io/dhbw-se-2023/yaac:master`
2.2 Podman `podman run -it --rm -v $XAUTHORITY:$XAUTHORITY:ro -v /tmp/.X11-unix:/tmp/.X11-unix:ro  -e "DISPLAY" ghcr.io/dhbw-se-2023/yaac:master`

Works on WSL, and linux using Xorg/X11 and/or Wayland.

**Comment by MaxAlberti** [comment]
WSL does not require the first step.

**Comment by Erix0815** [comment]
![image](https://github.com/DHBW-SE-2023/YAAC/assets/80325429/5ae8b9b5-c47b-4284-aedf-052ed7ee8319)

the given command does not work like this on wsl/docker
a temprary fix is to use
```
docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix:ro  -e "DISPLAY" ghcr.io/dhbw-se-2023/yaac:master
```

this works fine, albeit very laggy (might be because of virtualization)

**Comment by Erix0815** [comment]
after analyzing the output some more, i found that the $XAUTHORITY variable is empty, wich results in `$XAUTHORITY:$XAUTHORITY:ro` being converted to `::ro`, this causes the error when running the original command
![image](https://github.com/DHBW-SE-2023/YAAC/assets/80325429/093a84f4-37a6-482f-869b-ced833d426fb)

**Comment by MaxAlberti** [comment]
@Erix0815's comment only apply to WSL

**Comment by leandergmeiner** [comment]
No progress here. We can only use Docker
