### ISSUE TITLE
Homeview: Create a working Sidebar for the main UI window

### ISSUE THREAD

**Issue by MaxAlberti** [DHBW-SE-2023/YAAC#47]
The Sidebar and window size is specified in the mockup here #29

**Comment by danielSiegt08** [comment]
Working separately, will merge with https://github.com/DHBW-SE-2023/YAAC/issues/47 later.

Sidebar logic is already working. I'll setup the basic layout for the whole application following https://github.com/DHBW-SE-2023/YAAC/issues/29, so that the sidebar is capable to navigate between all pages.

**Comment by danielSiegt08** [comment]
First Implementation pushed on feature/hmi-fyne-layout branch. The designed Theme from issue #48 can now be merged.

**Comment by danielSiegt08** [comment]
Since the Sidebar has been implemented, this issue can be considered as closed.
