### ISSUE TITLE
[Bug] The executable panics when not started from the project's root directory

### ISSUE THREAD

**Issue by MaxAlberti** [DHBW-SE-2023/YAAC#50]
# Summary
The crash log leads me to believe that the cause of the error is the statically linked icon file we use for the tray icon. 
Fyne offers a tool to incorporate files into source code. See: https://docs.fyne.io/extend/bundle
# Goal
Remove error while maintaining window and tray icon

**Comment by leandergmeiner** [comment]
Was there any progress on this bug?

**Comment by MaxAlberti** [comment]
Bundling does in fact solve the problem. Will test some edge cases and meet with @danielSiegt08  before merging.

**Comment by MaxAlberti** [comment]
Waiting for https://github.com/DHBW-SE-2023/YAAC/pull/127/
