### ISSUE TITLE
Mail: trigger Image Processing

### ISSUE THREAD

**Issue by V1nzent** [DHBW-SE-2023/YAAC#55]
Trigger the image processing process with the binary of the image, that was extracted

**Comment by leandergmeiner** [comment]
This is implemented in the background demon task. It polls the E-Mail for anything new and then processes any new mails.
See #78

**Comment by leandergmeiner** [comment]
This is implemented in the background demon task. It polls the E-Mail for anything new and then processes any new mails.
See #78
