### ISSUE TITLE
Student View: Implement the Student View Layout

### ISSUE THREAD

**Issue by danielSiegt08** [DHBW-SE-2023/YAAC#61]
Since we made good progress implementing the homeview as well as the sidebar, we can now move on. 

The student view will provide the user with useful information about each student and their attendance over time. 
Following informations will be provided: 
- Course
- Name
- Student Attendance: 
   - Date
   - State of attendance

To gain this specific information the user will have the opportunity to select Course+Year by using the dropdown menus. 
The pages style will be aligned to the layout designed in #29.

**Comment by danielSiegt08** [comment]
Pushed first Student View layout to feauture/hmi-fyne-layout branch. 

Still missing: 
Functionalities to pull data from backend.

**Comment by EvaMatz** [comment]
Table is clickable and cells act as buttons (they shouldn't)

**Comment by leandergmeiner** [comment]
Basic code is implemented. Refactoring is done in another issue.
