### ISSUE TITLE
Homeview: Implement Settings View layout

### ISSUE THREAD

**Issue by danielSiegt08** [DHBW-SE-2023/YAAC#62]
The settings view will give the user the capability to configure the application freely. 
The user will be able to configure the following options: 
- "Allgemein": General Information
- "Datenbank": Restart database, Execute a new pull, Configure connection data
- "Email":  Restart mail Server, Execute a new pull, Configure connection data
- "Wiki/Doku": User Documentation + GitHub WIKI
- "Impressum"

The view will be designed as initially planned in #29

**Comment by danielSiegt08** [comment]
Pushed first layout to feature/hmi-fyne-layout branch. Layout is almost finished, functionalities missing.

**Comment by leandergmeiner** [comment]
Basic code is implemented. Refactoring is done in another issue.

**Comment by danielSiegt08** [comment]
After some consideration we decided on removing "Allgemein" and "Datenbank" since these won't hold necessary information and are therefore redundant.
