### ISSUE TITLE
Bugfix Frontend

### ISSUE THREAD

**Issue by EvaMatz** [DHBW-SE-2023/YAAC#68]
Headers are shown twice (e. g. Studenten - Studenten or Kurse - Kursansicht); one header would be enough

Sidebar: When clicking on a button to navigate to another view, old button remains coloured dark-grey (e. g. Home-> Übersicht: background of home button will remain grey)

Optional, nice-to-have: in Settings View: Move the second sidebar slightly up to align it with the first sidebar :)

![image](https://github.com/DHBW-SE-2023/YAAC/assets/114435451/a5cddd04-26aa-4996-903b-066b241e12a5)

**Comment by EvaMatz** [comment]
@MaxAlberti @danielSiegt08

**Comment by JonasZagst** [comment]
The fixes work for me (Arch Linux-lts)

**Comment by danielSiegt08** [comment]
Since the bugs seem to be removed, we'll close this issue.
