### ISSUE TITLE
Course View: Implement the Courses View Layout

### ISSUE THREAD

**Issue by danielSiegt08** [DHBW-SE-2023/YAAC#70]
The course view will provide the user with useful information about each course and their attendance at a certain date.
Following informations will be provided:

Course Names
Student Names
Student Attendance for a specific date

Therefore the following functionalities will be needed: 
- Date Picker Area
- Buttons to select the concerned course
- List to display the attendances
- Dropdown Menu to upload/edit or show a attendance list

The pages style will be aligned to the layout designed in https://github.com/DHBW-SE-2023/YAAC/issues/29.

**Comment by leandergmeiner** [comment]
Basic code is implemented. Refactoring is done in another issue.
