### ISSUE TITLE
[Bug] Significant delay when switching from the landing page to the overview

### ISSUE THREAD

**Issue by leandergmeiner** [DHBW-SE-2023/YAAC#75]
### Description
When I switch from the hompage to the overview page there is a significant delay to loading the content of this page, when compared to the other pages. I didn't time it but it feels like there is a delay of 300-500ms between clicking the overview button and the content actually loading. 

### System
- WSL2 with Ubuntu
- I ran the command `make run` to launch the application

**Comment by MaxAlberti** [comment]
@danielSiegt08 seems to have fixed this as an internal issue.
Still plan to bump up.
