### ISSUE TITLE
Branch protection and Repo security

### ISSUE THREAD

**Issue by leandergmeiner** [DHBW-SE-2023/YAAC#8]

**Comment by EvaMatz** [comment]
Both branches `master` and `dev` from YAAC are protected.
The rules state:
- Require a pull request before merging: All commits must be made to a non-protected branch and submitted via a pull request before they can be merged into a branch that matches this rule
- Lock branch: Branch is read-only. Users cannot push to the branch.
- Require approvals: Pull requests targeting a matching branch require a number of approvals and no changes requested before they can be merged.
> dev: 1 approval required
> master: 2 approvals required
- Do not allow bypassing the above settings. The above settings will apply to administrators and custom roles with the "bypass branch protections" permission.
