### ISSUE TITLE
Discussion: Should mail processing fail if no course was detected

### ISSUE THREAD

**Issue by leandergmeiner** [DHBW-SE-2023/YAAC#93]
### Description
Currently if the mail subject doesn't contain the course, the mail parsing fails with an error. Does this make sense?

**Comment by leandergmeiner** [comment]
I don't think that this makes sense, because the course should not be extracted from the mail subject, as it is entered by a human and they can make mistakes.
The list already has a header which contains the course, I think we should use that instead of the mail subject.

**Comment by leandergmeiner** [comment]
#86 is related to this issue.

**Comment by V1nzent** [comment]
I would agree. Should the course always be read from the list or only if the mail subject doesn't contain it?

**Comment by MaxAlberti** [comment]
Moved to discussion https://github.com/orgs/DHBW-SE-2023/discussions/98
